### PR TITLE
Fix logmessags for production

### LINKED ISSUE #103: Wrong log message
I made a fresh instance without any data. When I run `docker-compose up` the vote service writes something to the log that does not look like a correct message (`foo` is the name of my instance directory):
```
foo-vote-1             | 2022/02/21 12:17:28 Receive vote count request: &{GET /internal/vote/vote_count?id=0
HTTP/1.1 1 1 map[Accept-Encoding:[gzip] User-Agent:[Go-http-client/1.1]] {} <nil> 0 [] false vote:9013 map[] map[]
<nil> map[] 172.18.0.9:40806 /internal/vote/vote_count?id=0 <nil> <nil> <nil> 0xc00033adc0}
```
Is there really a Go http client running behind or is this just a bug?

### PR DESCRIPTION
**Pull request by ostcar**
Fixes #103

### CODE REVIEW

File: internal/vote/http.go [hunk 1]
```diff
@@ -117,7 +117,7 @@ func handleClearAll(mux *http.ServeMux, clear clearAller) {
 	mux.HandleFunc(
 		httpPathInternal+"/clear_all",
 		func(w http.ResponseWriter, r *http.Request) {
-			log.Info("Receive clear request: %v", r)
+			log.Info("Receiving clear all")
```
Comment (normanjaeckel) [inline internal/vote/http.go:120]: Missing word "request"

**Review by normanjaeckel — APPROVED** [review]
One minor change.

File: internal/vote/http.go (hunk 1 above)
Comment (ostcar) [reply internal/vote/http.go]: done
